export const getBrowserLang = () => {
  if (typeof navigator !== 'undefined') {
    const lang = navigator.language || (navigator as any).userLanguage;
    if (lang && lang.toLowerCase().startsWith('fr')) return 'fr';
  }
  return 'en';
};

const translations = {
  en: {
    // App.tsx
    'app.subtitle': "Audit the engineering profile of any developer.",
    'app.placeholder': "Type a GitHub username... (e.g., torvalds)",
    'app.analyze': "Analyze",
    'app.footer.desc': "Code Audit Engine & GitHub Profile Intelligence",
    'app.footer.powered': "Powered by GitHub REST API & Heuristic Engine",
    'app.tab.overview': "Overview & Radar",
    'app.tab.projects': "Digested Projects & READMEs",
    'app.tab.recruitment': "Recruitment Synthesis",
    'app.howItWorks': "How does it work?",
    
    // Navbar
    'nav.quota': "Quota / Token",
    'nav.export': "Export",
    'nav.history': "History",
    
    // ProfileHeader
    'profile.algorithm': "Algorithmic calculation",
    'profile.score': "Engineering score",
    'profile.repos': "public repos analyzed",
    'profile.velocity': "Estimated Code Velocity",
    
    // OverviewTab
    'overview.radar': "Skills Radar",
    'overview.pillars': "8 Pillars",
    'overview.strengths': "Major Strengths",
    'overview.growth': "Growth Opportunities",
    'overview.stack': "Mastered Tech Stack",
    'overview.stackDesc': "Extracted from code & READMEs",
    'overview.langDist': "Language Distribution",
    'overview.top': "Top",
    'overview.explore': "Explore the digested projects & READMEs",
    'overview.timeline': "Project Activity Timeline",
    'overview.timelineDesc': "Heuristic commit volume",
    'overview.heatmap': "Technology Heatmap",
    
    // ProjectsDigestTab
    'projects.complexity': "Technical Complexity",
    'projects.viewReadme': "View README",
    'projects.noDescription': "No description provided.",
    
    // RecruitmentTab
    'recruitment.title': "Recruitment Synthesis",
    'recruitment.execSummary': "Executive Summary",
    'recruitment.techQuestions': "Technical Interview Questions",
    'recruitment.archTopics': "Architectural Topics",
    'recruitment.softSkills': "Detected Soft Skills",
    'recruitment.outreach': "Outreach Message (Draft)",
    'recruitment.copy': "Copy",
    'recruitment.copied': "Copied!",
    'recruitment.relatedTo': "Related to",
    
    // ExportModal
    'export.title': "Export Audit Report",
    'export.copy': "Copy Markdown to clipboard",
    'export.download': "Download raw JSON",
    
    // SettingsModal
    'settings.title': "API Quota & Token Configuration",
    'settings.shared': "Shared Quota (Without Token)",
    'settings.sharedDesc': "Remaining queries for the whole site. Resets every hour.",
    'settings.private': "Private Quota (With Token)",
    'settings.privateDesc': "Use your own GitHub Personal Access Token (PAT) for up to 5,000 queries/hour. Your token is stored ONLY in your browser's localStorage.",
    'settings.save': "Save Token",
    'settings.remove': "Remove Token",
    
    // MethodologyModal
    'methodology.title': "How does DevScope work?",
    'methodology.desc': "DevScope does not use LLMs (Generative AI) to evaluate candidates. Scores, archetypes, and architectural analysis are generated by a strict heuristic system (algorithmic rules), ensuring absolute objectivity and reproducibility without artificial bias or hallucination.",
    'methodology.fetch': "Repo Fetching",
    'methodology.fetchDesc': "Extraction of the 100 most recently pushed public repositories. Passive forks are ignored.",
    'methodology.deepScan': "Deep Tree Scan",
    'methodology.deepScanDesc': "Interrogation of the Git tree (up to 5000 files per repo) to detect CI/CD (.github/workflows), IaC (terraform/), Tests (__tests__), and Dockerfiles.",
    'methodology.semantic': "Semantic Analysis",
    'methodology.semanticDesc': "Extraction of Topics and descriptions to map the project into one of the 5 engineering families.",
    'methodology.radar': "Radar Scoring",
    'methodology.radarDesc': "Points assigned strictly based on the presence of advanced technologies (e.g., k8s -> DevOps++, vitest -> Frontend++).",
    'methodology.limits': "Known Limitations",
    'methodology.limit1': "Private code is not visible. Developers working primarily on enterprise projects may be undervalued.",
    'methodology.limit2': "Giant repositories (like the Linux kernel) may exceed the API tree limit, masking some deep test files.",
  },
  fr: {
    // App.tsx
    'app.subtitle': "Auditez l'ingénierie de n'importe quel développeur.",
    'app.placeholder': "Taper un pseudo GitHub ici... (ex: torvalds)",
    'app.analyze': "Analyser",
    'app.footer.desc': "Moteur d'Audit de Code & Intelligence Profils GitHub",
    'app.footer.powered': "Propulsé par GitHub REST API & Moteur Heuristique",
    'app.tab.overview': "Vue d'Ensemble & Radar",
    'app.tab.projects': "Projets & READMEs Digérés",
    'app.tab.recruitment': "Synthèse Recrutement",
    'app.howItWorks': "Comment ça marche ?",
    
    // Navbar
    'nav.quota': "Quota / Token",
    'nav.export': "Exporter",
    'nav.history': "Historique",
    
    // ProfileHeader
    'profile.algorithm': "Calcul algorithmique",
    'profile.score': "Score d'ingénierie",
    'profile.repos': "dépôts publics analysés",
    'profile.velocity': "Vélocité estimée",
    
    // OverviewTab
    'overview.radar': "Radar de Compétences",
    'overview.pillars': "8 Piliers",
    'overview.strengths': "Points Forts Majeurs",
    'overview.growth': "Opportunités & Axes d'Évolution",
    'overview.stack': "Stack Technique Maîtrisée",
    'overview.stackDesc': "Extraite du code & READMEs",
    'overview.langDist': "Répartition des Langages",
    'overview.top': "principaux",
    'overview.explore': "Explorer les projets & READMEs digérés",
    'overview.timeline': "Timeline d'Activité Projets",
    'overview.timelineDesc': "Volume heuristique de commits",
    'overview.heatmap': "Heatmap Technologique",
    
    // ProjectsDigestTab
    'projects.complexity': "Complexité technique",
    'projects.viewReadme': "Voir le README",
    'projects.noDescription': "Aucune description fournie.",
    
    // RecruitmentTab
    'recruitment.title': "Synthèse Recrutement",
    'recruitment.execSummary': "Résumé Exécutif",
    'recruitment.techQuestions': "Questions d'Entretien Techniques",
    'recruitment.archTopics': "Sujets d'Architecture",
    'recruitment.softSkills': "Soft Skills Détectées",
    'recruitment.outreach': "Message d'Approche (Draft)",
    'recruitment.copy': "Copier",
    'recruitment.copied': "Copié !",
    'recruitment.relatedTo': "Lié à",
    
    // ExportModal
    'export.title': "Exporter le Rapport d'Audit",
    'export.copy': "Copier en Markdown",
    'export.download': "Télécharger le JSON brut",
    
    // SettingsModal
    'settings.title': "Configuration du Quota & Token API",
    'settings.shared': "Quota Partagé (Sans Token)",
    'settings.sharedDesc': "Requêtes restantes pour l'ensemble du site. Se réinitialise chaque heure.",
    'settings.private': "Quota Privé (Avec Token)",
    'settings.privateDesc': "Utilisez votre propre Personal Access Token (PAT) GitHub pour bénéficier de 5000 requêtes/heure. Votre token est stocké EXCLUSIVEMENT dans le localStorage de votre navigateur.",
    'settings.save': "Enregistrer le Token",
    'settings.remove': "Supprimer le Token",
    
    // MethodologyModal
    'methodology.title': "Comment fonctionne DevScope ?",
    'methodology.desc': "DevScope n'utilise pas de LLM (IA Générative) pour évaluer un candidat. Les scores, les archétypes et l'analyse d'architecture sont générés par un système heuristique pur (règles algorithmiques strictes), garantissant l'objectivité absolue et la reproductibilité des résultats sans biais artificiel ni hallucination.",
    'methodology.fetch': "Récupération des dépôts",
    'methodology.fetchDesc': "Extraction des 100 dépôts publics les plus récemment mis à jour. Les forks passifs sont ignorés.",
    'methodology.deepScan': "Scan profond de l'arborescence",
    'methodology.deepScanDesc': "Interrogation de l'arbre Git (jusqu'à 5000 fichiers) pour détecter la CI/CD (.github/workflows), l'IaC (terraform/), les Tests (__tests__) et les Dockerfiles.",
    'methodology.semantic': "Analyse sémantique",
    'methodology.semanticDesc': "Extraction des Topics et descriptions pour mapper le projet dans l'une des 5 familles d'ingénierie.",
    'methodology.radar': "Scoring Radar",
    'methodology.radarDesc': "Attribution de points strictement basée sur la présence de technologies avancées (ex: k8s -> DevOps++, vitest -> Frontend++).",
    'methodology.limits': "Limitations Connues",
    'methodology.limit1': "Le code privé n'est pas visible. Un développeur travaillant principalement en entreprise peut être sous-évalué.",
    'methodology.limit2': "Les dépôts géants (type Linux kernel) peuvent dépasser la limite d'arbre de l'API, masquant certains fichiers de test très profonds.",
  }
};

export const t = (key: string) => {
  const lang = getBrowserLang();
  return (translations[lang] as any)[key] || key;
};
